# Generated by Django 3.1 on 2020-09-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feed',
        ),
    ]
