# Generated by Django 3.1 on 2020-09-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0002_delete_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('thumbnail_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
