# Generated by Django 3.1 on 2020-09-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20200902_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
