# Generated by Django 3.1 on 2020-09-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20200902_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['-published_at'], name='feed_feed_publish_7c9ff4_idx'),
        ),
    ]
